{{ config(materialized='view') }}

select
    RECORD_ID,
    TIMESTAMP,
    CONTAINER_ID,
    SHIPMENT_ID,
    PRODUCT_NAME,
    ORIGIN_CITY,
    DESTINATION_CITY,
    TEMPERATURE_C,
    "Humidity_%",
    VIBRATION_LEVEL,
    TRAVEL_DISTANCE_KM,
    REMAINING_DISTANCE_KM,
    TRANSIT_TIME_HOURS,
    SHELF_LIFE_REMAINING_HOURS,
    "Spoilage_Risk_%",
    QUALITY_SCORE,
    PRODUCT_WEIGHT_KG,
    MARKET_PRICE_PER_KG,
    ESTIMATED_REVENUE,
    ESTIMATED_LOSS,
    ARBITRAGE_PROFIT,
    RECOMMENDED_ACTION,
    ALERT_LEVEL
from ATMOSYNC_DB.RAW_DATA.RAW_IOT_DATA